### ISSUE TITLE
Class 'SOSTheBlack\Moip\Facades\Moip' not found

### ISSUE THREAD

**Issue by giovannefc** [SOSTheBlack/moip#20]
Olá.

Instalei normalmente aqui o pacote, coloquei nos providers e aliases certinho, mas na hora de usar recebo esse erro:

<code>Class 'SOSTheBlack\Moip\Facades\Moip' not found</code>

Inclusive no seu exemplo, tá:

<code>Moip::sendMoip($data);</code>

O alias, está MoipApi, então chamei a classe assim:

<code>MoipApi::sendMoip($data);</code>

Aí dá o erro que postei acima, chequei e os arquivos estão lá na pasta vendor.

O que está errado será?

Obrigado.

**Comment by SOSTheBlack** [comment]
Olá

De um composer update por favor e veja se o erro do Facade será selecionado.
Infelizmente o readme.md está um pouco confuso e desatualizado, irei criar um wiki para facilitar.

Para criar uma order no moip o correto seria
```
MoipApi::postOrder($data);
```

**Comment by giovannefc** [comment]
Olá Jean, obrigado pela resposta. Então.. Eu estava usando a versão estável, resolvi instalar a versão dev. Daí funcionou. Não deu mais erros.

Mas na verdade eu preciso fazer uma integração transparente, para a pessoa fazer tudo pelo meu site sem precisar passar pelo site do Moip. Mas como você disse, não tem muita informação sobre no momento para o que preciso.

Você pode me ajudar? Aí já testamos a versão dev. Eu já tenho a conta no Moip sandbox para testes. Basicamente, seria assim: A pessoa coloca os dados de pagamento no formulário, processamos o pagamento com a Api do Moip e se retornar true, redirecionamos para uma página de sucesso. Quais funcões/metódos da Api usaremos nesse caso?

Eu até tentei usar a Api direto deles, mas ele faz instâncias da classe <code>SimpleXmlElement </code> que faz parte daquele <code>phpQuery</code>.. aí já complicou tudo..

**Comment by SOSTheBlack** [comment]
O problema do issue foi resolvido então ele será fechado.
Abre outro issue com este comentário que lhe darei orientações para teste por lá
abrss
