### ISSUE TITLE
Como passar os dados do cartão de crédito para o Checkout Transparente?

### ISSUE THREAD

**Issue by blumtech** [SOSTheBlack/moip#26]
Olá,
Depois de fazer a chamada MoipApi::postOrder($data)
O retorno é um objeto 
stdClass Object ( [getXML] [replyXML] [token] [url] )

Se o cliente for redirecionado para a url MoipApi::response()->url ele consegue fazer o pagamento. 
Como eu faço para processar o pagamento de forma transparente?

**Comment by SOSTheBlack** [comment]
De uma olhada nessa documentação básica e vê se ela lhe ajuda

https://github.com/SOSTheBlack/moip/wiki/Checkout-transparente

Confira este vídeo também

https://www.youtube.com/watch?v=nDUQCNWTups

**Comment by blumtech** [comment]
Perfeito!
O pagamento tem que ser processado via JS? 
Não tem como processar no servidor e só passar o resultado para o front?
obrigado!

**Comment by SOSTheBlack** [comment]
Boa tarde Igor

 

O pagamento deve ser processado via JS.

Não há outra forma

 

De: Igor Blumberg [mailto:notifications@github.com] 
Enviada em: quarta-feira, 25 de março de 2015 15:07
Para: SOSTheBlack/moip
Cc: Jean C. Garcia
Assunto: Re: [moip] Como passar os dados do cartão de crédito para o Checkout Transparente? (#26)

 

Perfeito!
O pagamento tem que ser processado via JS? 
Não tem como processar no servidor e só passar o resultado para o front?
obrigado!
