### ISSUE TITLE
var_dump no arquivo API.php

### ISSUE THREAD

**Issue by grupouds-andre** [SOSTheBlack/moip#28]
Versão 1.2.1

Há um var_dump que está sobrando no meio do código, mais precisamente na linha 663.
https://github.com/SOSTheBlack/moip/blob/master/src/SOSTheBlack/Moip/Api.php#L663
```
    $this->setError('Error: Maximum amount can not be greater than 12.');

    var_dump($receipt);
    $parcela->addChild('Recebimento', $this->receipt($receipt));
```

**Comment by SOSTheBlack** [comment]
Vlw.
https://github.com/SOSTheBlack/moip/commit/9925013c71b07c4f9f06e6a4f3a78617fe6f936f
